### ISSUE TITLE
Question about two disabled services and what they do. "pci-latency.service" and "optimize-interruptfreq.service"

### ISSUE THREAD

**Issue by rizzini** [SoongVilda/archlinux-performance#2]
Hey, man.. Could elaborate a bit on the `pci-latency.service`, `optimize-interruptfreq.service` and `ksmd.service/.timer`? What are they exactly? They're disabled.

About `optimize-interruptfreq.service`, currently in my system both values are 64. The service pushes them to 3072. `ksmd.service/.timer` seems to enable ksm on boot, but, as far as I checked online, `0` disable and `1` enabled it. What's does `8` do for it? I didn't enable them yet.

**Comment by SoongVilda** [comment]
Hey, thanks for the follow-up. I'm going to check on the CachyOS side. I'll let you know soon.

**Comment by ptr1337** [comment]
> Hey, man.. Could elaborate a bit on the `pci-latency.service`, `optimize-interruptfreq.service` and `ksmd.service/.timer`? What are they exactly? They're disabled.
> 
> About `optimize-interruptfreq.service`, currently in my system both values are 64. The service pushes them to 3072. `ksmd.service/.timer` seems to enable ksm on boot, but, as far as I checked online, `0` disable and `1` enabled it. What's does `8` do for it? I didn't enable them yet.

These services are simply not considered to be stable at every hardware, so we don't enabled them as default and the user can simply enable/disable them on there own.

The ksmd.service is a alternative to the uksmd.service. Both require special patches.
Since uksmd is currently not working together with the maple tree and we are waiting for a upstream fix, user can use the ksmd.service, which sets the "8" as the run file.

The 8 enables a automatic ksm mechanism, which is doing work when a memory threshold from 20% is reached. This value can also be changed to a different one, for example 40%.
https://github.com/CachyOS/kernel-patches/blob/master/6.0/0016-ksm.patch#L151-L505

**Comment by rizzini** [comment]
`Both require special patches.`

I patched my kernel, which now I realize it might not be just the final work, but it does touch the `/sys/kernel/pmadv/ksm`. Anyway, I'm over my head here. I'll try your patch and see how it goes. If not, I'll just wait. Thanks for your time, guys.
